[package]
name = "wasm"
version = "0.0.1"
authors = ["DimejiSR <Wesbitty Inc>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["swc_v1"]
swc_v1 = []


[dependencies]
wasm-bindgen = "0.2.63"
wesjet-swc = { version = "0.0.1", path = "../core" }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

# Disable 'wasm-opt' to fix build error
[package.metadata.wasm-pack.profile.release]
wasm-opt = false
