import Link from 'next/link'
import Head from 'next/head'
import styles from '~/styles/App.module.css'
import { Inter } from 'next/font/google'
import { compareDesc, format, parseISO } from 'date-fns'
// @ts-ignore
import { allPosts, Post } from 'wesjet/static'

const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps() {
  // @ts-ignore
  const posts: Post[] = allPosts.sort((a, b) => {
    return compareDesc(new Date(a.date), new Date(b.date))
  })
  return { props: { posts } }
}

function PostCard(post: Post) {
  return (
    <div className={styles.card}>
      <h2>
        <Link href={post.url}>{post.title}</Link>
      </h2>
      <time dateTime={post.date} className="mb-2 block text-xs text-gray-600">
        {format(parseISO(post.date), 'LLLL d, yyyy')}
      </time>
      <p dangerouslySetInnerHTML={{ __html: post.body.html }} />
    </div>
  )
}

export default function Home({ posts }: { posts: Post[] }) {
  return (
    <>
      <Head>
        <title>Create Wesjet App</title>
        <meta name="description" content="Generated by create wesjet app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>Wesjet Example</p>
        </div>

        <div className={styles.grid}>
          {posts.map((post, idx) => (
            <PostCard key={idx} {...post} />
          ))}
        </div>
      </main>
    </>
  )
}
