name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["template: bug"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: markdown
    attributes:
      value: |
        *Note:* If you leave out sections, the issue might be moved to the ["Help" section](https://github.com/wesbitty/wesjet/discussions/categories/help).
        [examples](https://github.com/wesbitty/wesjet/tree/automated/examples) related issue should be reported using [this](https://github.com/wesbitty/wesjet/issues/new?assignees=&labels=type%3A+example%2Ctemplate%3A+bug&template=2.example_bug_report.yml) issue template instead.
        Feature requests should be opened as [discussions](https://github.com/wesbitty/wesjet/discussions/new?category=ideas). [Read more](https://github.com/Wesbitty/wesjet/blob/automated/contributing/core/adding-features.md).
  - type: checkboxes
    attributes:
      label: Wesjet Latest release
      description: 'Please run `npm install wesjet@latest` to try the latest version of Wesjet that ships daily. It includes all features and fixes that have not been released to the stable version yet. Some issues may already be fixed in the automated version, so please verify that your issue reproduces before opening a new issue.'
      options:
        - label: I verified that the issue exists in the latest Wesjet release
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 0.0.30 (Default)
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Which area(s) of Wesjet are affected? (leave empty if unsure)
      multiple: true
      options:
        - 'CLI (create-wesjet-app)'
        - 'ESLint (eslint-plugin-wesjet)'
        - 'Static imports (wesjet/static)'
        - 'Using Wesjet in Monorepo'
        - 'Wesjet Next.js Configuration (wesjet/next)'
        - 'Wesjet Configuration (wesjet.config.[ts/js])'
        - 'Wesjet MakeReload (wesjet/next/hook)'
        - 'Wesjet MakeMdx (wesjet/next/hook)'
        - 'TypeScript Configuration (paths, include)'
  - type: input
    attributes:
      label: Link to the code that reproduces this issue
      description: |
        A link to a GitHub repository, a [CodeSandbox](https://codesandbox.io/p/sandbox/github/wesbitty/wesjet/tree/automated/examples/reproduction-template) or a [StackBlitz](https://stackblitz.com/fork/github/wesbitty/wesjet/tree/automated/examples/reproduction-template) minimal reproduction. Minimal reproductions should be created from our [bug report template with `npx create-next-app -e reproduction-template`](https://github.com/wesbitty/wesjet/tree/automated/examples/reproduction-template) and should include only changes that contribute to the issue.
        To report an App Router related issue, you can use these templates: [CodeSandbox](https://codesandbox.io/p/sandbox/github/wesbitty/wesjet/tree/automated/examples/reproduction-template-app-dir), [StackBlitz](https://stackblitz.com/fork/github/wesbitty/wesjet/tree/automated/examples/reproduction-template-app-dir) or [`npx create-wesjet-app -e reproduction-template-app-dir`](https://github.com/wesbitty/wesjet/tree/automated/examples/reproduction-template-app-dir)
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior, please provide a clear description of how to reproduce the issue, based on the linked minimal reproduction. Screenshots can be provided in the issue body below. If using code blocks, make sure that [syntax highlighting is correct](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) and double check that the rendered preview is not broken.
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/wesbitty/wesjet/blob/automated/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
