blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/wesbitty/wesjet/discussions
    about: Please ask and answer questions here.
  - name: Feature Request
    url: https://github.com/wesbitty/wesjet/discussions/new?category=ideas
    about: Feature requests should be opened as discussions
