name: Crates

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Build Crates
        run: cargo build --verbose
        working-directory: packages/@wesjet/swc

      - name: Test Crates
        run: cargo test --verbose
        working-directory: packages/@wesjet/swc
